### ISSUE TITLE
Stop CircularProgressView animation? 

### ISSUE THREAD

**Issue by bdaykid** [rahatarmanahmed/CircularProgressView#28]
Hello, thank you for the great lib. I was wandering how to stop the animation of the circularprogressview. The only way i found is just setting its visibility to GONE. Is there a way to stop the animation? Or if i miss something can you point me the right way? I'm quite new to android. So my worries are if it just hide the animation and doesn't stop it, won't it eat the resources of the device? Thank you.

**Comment by rahatarmanahmed** [comment]
CPV doesn't have a way to do this yet. Pausing the animation calculations was only added in [API level 19](http://developer.android.com/reference/android/animation/ValueAnimator.html#pause()), so that's not really feasible. However, I suspect Android doesn't call paint() on hidden Views.

I'm not the most experienced with Android either so I don't have a clear answer for you.

**Comment by bdaykid** [comment]
I see. Thank u very much for your quick response! All the best.
