### ISSUE TITLE
How to mimic the default Lollipop's look?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [rahatarmanahmed/CircularProgressView#9]
as the title says. What are the configurations for this?
Also, can I make it so that if newer versions of Android arrive, it will use their default style and not the one of the library?

**Comment by rahatarmanahmed** [comment]
The defaults come very close to the default look. The only big difference
is the color, and that likely depends on your theme's color. There is a PR
for using the theme color so that will be in soon.

The timing of the animation duration is slightly off but I came as close as
I could playing it by eye. The shape of the animation should remain the
same I'd you keep the default number of steps.

**Comment by AndroidDeveloperLB** [comment]
Can you also add support for older versions of Android, like the support library?

**Comment by rahatarmanahmed** [comment]
Since the color changes based on your theme, for now you just have to set the color to match your theme's accent. In the next release this will happen automatically, and should hopefully support the support library as well.

**Comment by AndroidDeveloperLB** [comment]
ok, I've decided to use a different library (this: https://github.com/fengdai/AlertDialogPro ). Sorry for all the trouble/time. And thank you.
